
/* Drop Tables */

DROP TABLE IF EXISTS AUTHORITIES;
DROP TABLE IF EXISTS USERS;




/* Create Tables */

CREATE TABLE USERS
(
	USER_ID VARCHAR(32) NOT NULL,
	USERNAME VARCHAR(32) NOT NULL,
	PASSWORD CHAR(80) NOT NULL,
	PASSWORD_UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	ENABLED BOOLEAN NOT NULL,
	INTERIM_REGISTER BOOLEAN NOT NULL,
	LOGIN_ERROR_COUNT INT NOT NULL,
	LOCKOUT_TIMESTAMP TIMESTAMP,
	LAST_LOGIN_TIMESTAMP TIMESTAMP,
	LOGOUT_TIMESTAMP TIMESTAMP,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INT NOT NULL,
	PRIMARY KEY (USER_ID)
) WITHOUT OIDS;


CREATE TABLE AUTHORITIES
(
	USER_ID VARCHAR(32) NOT NULL,
	AUTHORITY VARCHAR(50) NOT NULL,
	REGISTER_TIMESTAMP TIMESTAMP NOT NULL,
	REGISTER_USER_ID VARCHAR(32) NOT NULL,
	UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
	UPDATED_USER_ID VARCHAR(32) NOT NULL,
	VERSION INT NOT NULL,
	PRIMARY KEY (USER_ID, AUTHORITY)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE AUTHORITIES
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USERS (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON TABLE USERS IS 'ユーザ';
COMMENT ON COLUMN USERS.USER_ID IS 'ユーザID';
COMMENT ON COLUMN USERS.USERNAME IS 'ユーザ名';
COMMENT ON COLUMN USERS.PASSWORD IS 'パスワード';
COMMENT ON COLUMN USERS.PASSWORD_UPDATED_TIMESTAMP IS 'パスワード更新日時';
COMMENT ON COLUMN USERS.ENABLED IS '有効フラグ';
COMMENT ON COLUMN USERS.INTERIM_REGISTER IS '仮登録フラグ';
COMMENT ON COLUMN USERS.LOGIN_ERROR_COUNT IS 'ログインエラー回数';
COMMENT ON COLUMN USERS.LOCKOUT_TIMESTAMP IS 'ロックアウト日時';
COMMENT ON COLUMN USERS.LAST_LOGIN_TIMESTAMP IS '最終ログイン日時';
COMMENT ON COLUMN USERS.LOGOUT_TIMESTAMP IS 'ログアウト日時';
COMMENT ON COLUMN USERS.REGISTER_TIMESTAMP IS '登録日時';
COMMENT ON COLUMN USERS.REGISTER_USER_ID IS '登録ユーザID';
COMMENT ON COLUMN USERS.UPDATED_TIMESTAMP IS '更新日時';
COMMENT ON COLUMN USERS.UPDATED_USER_ID IS '更新ユーザID';
COMMENT ON COLUMN USERS.VERSION IS 'バージョン';
COMMENT ON TABLE AUTHORITIES IS '権限';
COMMENT ON COLUMN AUTHORITIES.USER_ID IS 'ユーザID';
COMMENT ON COLUMN AUTHORITIES.AUTHORITY IS '権限';
COMMENT ON COLUMN AUTHORITIES.REGISTER_TIMESTAMP IS '登録日時';
COMMENT ON COLUMN AUTHORITIES.REGISTER_USER_ID IS '登録ユーザID';
COMMENT ON COLUMN AUTHORITIES.UPDATED_TIMESTAMP IS '更新日時';
COMMENT ON COLUMN AUTHORITIES.UPDATED_USER_ID IS '更新ユーザID';
COMMENT ON COLUMN AUTHORITIES.VERSION IS 'バージョン';



